"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import CustomerNav from "@/components/customer/CustomerNav";
import {supabase} from "@/lib/supabase";

export default function OrderDetailPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [order,setOrder]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession(); if(!session)return router.replace("/login"); const r=await fetch("/api/customer/orders/"+id,{headers:{Authorization:"Bearer "+session.access_token},cache:"no-store"}); const b=await r.json(); if(!r.ok){setError(b.error||"Unable to load order.");setLoading(false);return} setOrder(b.order);setLoading(false)})()},[id,router]);
 if(loading)return <main className="min-h-screen bg-slate-50"><CustomerNav/><div className="mx-auto max-w-5xl px-5 py-10 text-slate-500">Loading order…</div></main>;
 if(error||!order)return <main className="min-h-screen bg-slate-50"><CustomerNav/><div className="mx-auto max-w-5xl px-5 py-10"><p className="text-red-600">{error||"Order not found."}</p></div></main>;
 const f=Array.isArray(order.fulfillment_orders)?order.fulfillment_orders[0]:order.fulfillment_orders;
 return <main className="min-h-screen bg-slate-50"><CustomerNav/><div className="mx-auto max-w-5xl px-5 py-10"><Link href="/account/orders" className="text-sm font-bold text-blue-600">← Back to orders</Link><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-col gap-5 sm:flex-row"><div className="h-28 w-28 shrink-0 overflow-hidden rounded-xl bg-slate-100">{order.product?.fotos?.[0]&&<img src={order.product.fotos[0]} alt="" className="h-full w-full object-cover"/>}</div><div><h1 className="text-2xl font-extrabold text-[#16294F]">{order.product?.nome||"Order"}</h1><p className="mt-2 text-sm text-slate-500">Order placed {new Date(order.vendido_em).toLocaleString()}</p><p className="mt-2 font-bold">R {Number(order.valor_venda||0).toFixed(2)}</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Payment</p><p className="mt-1 font-bold text-slate-900">{order.status||"Processing"}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Delivery</p><p className="mt-1 font-bold text-slate-900">{f?.status||"Processing"}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Quantity</p><p className="mt-1 font-bold text-slate-900">{order.quantity}</p></div></div>{f?.public_tracking_token&&<Link href={"/rastreio/"+f.public_tracking_token} className="mt-6 inline-flex rounded-xl bg-[#16294F] px-5 py-3 font-bold text-white">Track delivery</Link>}{f?.status==="delivered"&&<Link href={"/account/reviews"} className="ml-3 mt-6 inline-flex rounded-xl border border-[#16294F] px-5 py-3 font-bold text-[#16294F]">Review product</Link>}</div></div></main>;
}
