"use client";
import {Suspense,useEffect,useState} from "react"; import {useRouter,useSearchParams} from "next/navigation"; import Link from "next/link"; import CustomerNav from "@/components/customer/CustomerNav"; import {supabase} from "@/lib/supabase";
function CheckoutContent(){
 const router=useRouter(), params=useSearchParams(); const productId=params.get("product")||""; const quantity=Math.max(1,Math.min(50,Number(params.get("qty")||1)));
 const [product,setProduct]=useState<any>(null); const [form,setForm]=useState({full_name:"",phone:"",province:"",city:"",postal_code:"",address:"",address_reference:""}); const [loading,setLoading]=useState(true); const [paying,setPaying]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return router.replace("/login");const {data:p}=await supabase.from("products").select("id,nome,preco,preco_promocional,moeda,fotos,ativo,supplier_status").eq("id",productId).maybeSingle();if(!p||!p.ativo||p.supplier_status!=="approved"){setError("Product unavailable.");setLoading(false);return}setProduct(p);const {data:a}=await supabase.from("customer_addresses").select("*").eq("user_id",session.user.id).eq("is_default",true).maybeSingle();if(a)setForm({full_name:a.full_name,phone:a.phone,province:a.province,city:a.city,postal_code:a.postal_code||"",address:a.address,address_reference:a.address_reference||""});else {const {data:profile}=await supabase.from("profiles").select("full_name,phone_number,phone_e164").eq("id",session.user.id).maybeSingle();if(profile)setForm(f=>({...f,full_name:profile.full_name||"",phone:profile.phone_e164||profile.phone_number||""}))}setLoading(false)})()},[productId,router]);
 async function pay(e:any){e.preventDefault();setError("");setPaying(true);const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace("/login");return}const r=await fetch("/api/customer/checkout",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify({product_id:productId,quantity,...form})});const b=await r.json();if(!r.ok){setError(b.error||"Checkout failed.");setPaying(false);return}window.location.href=b.checkout_url}
 if(loading)return <main className="min-h-screen grid place-items-center">Loading checkout...</main>;
 const price=Number(product?.preco_promocional||product?.preco||0), total=price*quantity;
 return <main className="min-h-screen bg-[#f6f9fc]"><CustomerNav/><div className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-3xl font-extrabold text-[#0e1f3d]">Secure checkout</h1><div className="mt-8 grid gap-7 lg:grid-cols-[1fr_360px]"><form onSubmit={pay} className="rounded-[12px] border border-slate-200 bg-white p-6 space-y-4"><h2 className="text-xl font-bold text-[#0e1f3d]">Delivery details</h2>{Object.entries(form).map(([k,v])=><input key={k} required={["full_name","phone","province","city","address"].includes(k)} placeholder={k.replaceAll("_"," ")} value={String(v)} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full rounded-[7px] border border-slate-200 px-4 py-3"/>) }{error&&<div className="rounded-[7px] bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}<button disabled={paying} className="w-full rounded-[7px] bg-[#0e4aab] py-4 font-extrabold text-white disabled:opacity-60">{paying?"Redirecting to payment...":"Continue to secure payment"}</button></form><aside className="rounded-[12px] border border-slate-200 bg-white p-6 h-fit">{product?.fotos?.[0]&&<img src={product.fotos[0]} alt="" className="aspect-square w-full rounded-[7px] object-cover"/>}<h2 className="mt-4 font-extrabold text-[#0e1f3d]">{product?.nome}</h2><p className="mt-2 text-sm text-slate-500">Quantity: {quantity}</p><div className="mt-5 flex justify-between border-t pt-4 font-extrabold"><span>Total</span><span>R {total.toFixed(2)}</span></div><p className="mt-3 text-xs text-slate-400">Delivery is calculated from the supplier's South African shipping rules.</p></aside></div></div></main>
}


export default function CheckoutPage(){
 return <Suspense fallback={<main className="min-h-screen grid place-items-center">Loading checkout...</main>}><CheckoutContent/></Suspense>;
}
