"use client";
import {useEffect,useState} from "react"; import Link from "next/link"; import {useRouter} from "next/navigation"; import CustomerNav from "@/components/customer/CustomerNav"; import {supabase} from "@/lib/supabase";
export default function CartPage(){
 const router=useRouter(); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return router.replace("/login");const {data}=await supabase.from("customer_cart_items").select("id,product_id,quantity,products(id,nome,slug,preco,preco_promocional,fotos,moeda,estoque,ativo,supplier_status)").eq("user_id",user.id).order("created_at",{ascending:false});setItems(data||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function update(id:string,q:number){if(q<1){await supabase.from("customer_cart_items").delete().eq("id",id)}else await supabase.from("customer_cart_items").update({quantity:Math.min(50,q),updated_at:new Date().toISOString()}).eq("id",id);void load()}
 const total=items.reduce((s,i)=>s+Number(i.products?.preco_promocional||i.products?.preco||0)*i.quantity,0);
 return <main className="min-h-screen bg-[#f6f9fc]"><CustomerNav/><div className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-3xl font-extrabold text-[#0e1f3d]">Shopping cart</h1>{loading?<p className="mt-8">Loading...</p>:items.length===0?<div className="mt-8 rounded-[12px] border bg-white p-10 text-center"><p className="font-bold">Your cart is empty.</p><Link href="/marketplace" className="mt-4 inline-block rounded-[7px] bg-[#0e4aab] px-5 py-3 font-bold text-white">Continue shopping</Link></div>:<div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-4">{items.map(i=><div key={i.id} className="flex gap-4 rounded-[12px] border border-slate-200 bg-white p-4">{i.products?.fotos?.[0]&&<img src={i.products.fotos[0]} alt="" className="h-24 w-24 rounded-[7px] object-cover"/>}<div className="min-w-0 flex-1"><Link href={"/produto/"+i.products.slug} className="font-extrabold text-[#0e1f3d]">{i.products.nome}</Link><p className="mt-1 font-bold">R {Number(i.products.preco_promocional||i.products.preco||0).toFixed(2)}</p><div className="mt-3 flex items-center gap-3"><button onClick={()=>update(i.id,i.quantity-1)} className="h-8 w-8 rounded border">−</button><span>{i.quantity}</span><button onClick={()=>update(i.id,i.quantity+1)} className="h-8 w-8 rounded border">+</button></div></div></div>)}</div><aside className="h-fit rounded-[12px] border border-slate-200 bg-white p-6"><div className="flex justify-between text-lg font-extrabold"><span>Subtotal</span><span>R {total.toFixed(2)}</span></div><p className="mt-2 text-xs text-slate-500">For now checkout is completed per product so supplier shipping and fulfillment remain accurate.</p>{items.length===1&&<Link href={"/checkout?product="+encodeURIComponent(items[0].product_id)+"&qty="+items[0].quantity} className="mt-5 block rounded-[7px] bg-[#0e4aab] py-3 text-center font-bold text-white">Checkout</Link>}</aside></div>}</div></main>
}
