"use client";
import {useEffect,useState} from "react"; import {useRouter} from "next/navigation"; import CustomerNav from "@/components/customer/CustomerNav"; import {supabase} from "@/lib/supabase";
const empty={label:"Home",full_name:"",phone:"",province:"",city:"",postal_code:"",address:"",address_reference:"",is_default:false};
export default function AddressesPage(){
 const router=useRouter(); const [items,setItems]=useState<any[]>([]); const [form,setForm]=useState(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return router.replace("/login");const {data}=await supabase.from("customer_addresses").select("*").eq("user_id",user.id).order("is_default",{ascending:false}).order("created_at",{ascending:false});setItems(data||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function save(e:any){e.preventDefault();setSaving(true);const {data:{user}}=await supabase.auth.getUser();if(!user)return; if(form.is_default)await supabase.from("customer_addresses").update({is_default:false}).eq("user_id",user.id);const {error}=await supabase.from("customer_addresses").insert({...form,user_id:user.id});setSaving(false);if(error)alert(error.message);else{setForm(empty);void load()}}
 async function remove(id:string){await supabase.from("customer_addresses").delete().eq("id",id);void load()}
 return <main className="min-h-screen bg-slate-50"><CustomerNav/><div className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-3xl font-extrabold text-[#16294F]">Delivery addresses</h1><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-6 space-y-4"><h2 className="font-bold">Add address</h2>{Object.entries(form).filter(([k])=>!["is_default"].includes(k)).map(([k,v])=><input key={k} placeholder={k.replaceAll("_"," ")} value={String(v)} onChange={e=>setForm({...form,[k]:e.target.value})} className="w-full rounded-xl border border-slate-200 px-4 py-3"/>) }<label className="flex gap-2 text-sm"><input type="checkbox" checked={form.is_default} onChange={e=>setForm({...form,is_default:e.target.checked})}/> Set as default</label><button disabled={saving} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white">{saving?"Saving...":"Save address"}</button></form><div className="space-y-4">{loading?<p>Loading...</p>:items.map(a=><div key={a.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><div><p className="font-bold">{a.label} {a.is_default&&<span className="ml-2 text-xs text-blue-600">DEFAULT</span>}</p><p className="mt-2 text-sm text-slate-600">{a.full_name} · {a.phone}<br/>{a.address}, {a.city}, {a.province} {a.postal_code||""}</p></div><button onClick={()=>remove(a.id)} className="text-sm font-bold text-red-500">Delete</button></div></div>)}</div></div></div></main>
}
