"use client";

import LiveDataPage from "@/components/dashboard/LiveDataPage";
import { getAffiliateSales } from "@/lib/newvelion-api";

export default function SellerCommissionsPage() {
  return (
    <LiveDataPage
      area="seller"
      activeKey="commissions"
      title="Commissions"
      subtitle="Commission activity generated by your sales."
      loader={getAffiliateSales}
    />
  );
}
